server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/user/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/v1/auth/**
          filters:
            - StripPrefix=1

        - id: QuoteService
          uri: lb://QuoteService
          predicates:
            - Path=/api/quote/**
          filters:
            - StripPrefix=1
      globalcors:
      cors-configurations:
        '/**':
        allowed-origin-patterns: "http://127.0.0.1:*" # Allow all localhost ports
        allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        allowed-headers: "*"
        allow-credentials: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG